[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Use Edge Functions for bot detection
[[edge_functions]]
  function = "prerender"
  path = "/*"

# Fallback to SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200