[build]
  command = "npm run build"
  publish = "dist"

# Prerender.io integration for social media crawlers
[[redirects]]
  from = "/*"
  to = "https://service.prerender.io/YOUR_PRERENDER_TOKEN/https://yoursite.com/:splat"
  status = 200
  conditions = {User-Agent = ["googlebot*", "bingbot*", "yandex*", "baiduspider*", "facebookexternalhit*", "twitterbot*", "rogerbot*", "linkedinbot*", "embedly*", "quora*", "showyoubot*", "outbrain*", "pinterest*", "developers.google.com*", "slackbot*", "vkShare*", "W3C_Validator*", "redditbot*", "applebot*", "whatsapp*", "flipboard*", "tumblr*", "bitlybot*", "skypeuripreview*", "nuzzel*", "discordbot*", "google page speed*", "qwantify*", "pinterestbot*", "bitrix*"]}

# Default SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200