[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  function = "prerender"
  path = "/*"
  excludedPath = [
    "/.netlify/functions/*",
    "/favicon.ico",
    "/assets/*",
    "/static/*",
    "/robots.txt",
    "/sitemap.xml"
  ]

# SPA fallback (doesn't affect /.netlify/functions/*)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
