/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ContextNewImport } from './routes/context/new'
import { Route as ContextVideoVideoIdImport } from './routes/context/video.$videoId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContextNewRoute = ContextNewImport.update({
  id: '/context/new',
  path: '/context/new',
  getParentRoute: () => rootRoute,
} as any)

const ContextVideoVideoIdRoute = ContextVideoVideoIdImport.update({
  id: '/context/video/$videoId',
  path: '/context/video/$videoId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/context/new': {
      id: '/context/new'
      path: '/context/new'
      fullPath: '/context/new'
      preLoaderRoute: typeof ContextNewImport
      parentRoute: typeof rootRoute
    }
    '/context/video/$videoId': {
      id: '/context/video/$videoId'
      path: '/context/video/$videoId'
      fullPath: '/context/video/$videoId'
      preLoaderRoute: typeof ContextVideoVideoIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/context/new': typeof ContextNewRoute
  '/context/video/$videoId': typeof ContextVideoVideoIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/context/new': typeof ContextNewRoute
  '/context/video/$videoId': typeof ContextVideoVideoIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/context/new': typeof ContextNewRoute
  '/context/video/$videoId': typeof ContextVideoVideoIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/context/new' | '/context/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/context/new' | '/context/video/$videoId'
  id: '__root__' | '/' | '/context/new' | '/context/video/$videoId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextNewRoute: typeof ContextNewRoute
  ContextVideoVideoIdRoute: typeof ContextVideoVideoIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextNewRoute: ContextNewRoute,
  ContextVideoVideoIdRoute: ContextVideoVideoIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/context/new",
        "/context/video/$videoId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/context/new": {
      "filePath": "context/new.tsx"
    },
    "/context/video/$videoId": {
      "filePath": "context/video.$videoId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
